name = "BlastLCA"
uuid = "59c79803-3a52-40d7-aec0-3a5c885b2802"
authors = ["banhbio <ban@kuicr.kyoto-u.ac.jp>"]
version = "0.1.0"

[deps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
